from matplotlib.colors import ListedColormap
import matplotlib as mpl
import matplotlib.pyplot as plt
from itertools import cycle
from typing import Dict
import pandas as pd
import numpy as np

COLOR_DICT = {
    "爱瑞卓恩那罗共同目标": "darkorange",
    "恩那罗独有目标": "#BB2549",
    "爱瑞卓独有目标": "darkgreen",
    "恩那罗目标": "#BB2549",
    "恩那罗非目标": "grey",
    "恩那罗": "#BB2549",
    "爱瑞卓": "darkgreen",
    "地奥氨贝": "navy",
    "贝那普利氨氯地平片": "navy",
    "百安新": "crimson",
    "开素达": "darkgreen",
    "倍博特": "darkorange",
    "天舒平": "olivedrab",
    "协安之": "purple",
    "瑞心安": "teal",
    "思卫卡": "deepskyblue",
    "缬沙坦氨氯地平（百奥）": "gold",
    "缬沙坦氨氯地平（华新）": "violet",
    "缬氨悦": "coral",
    "未填写": "grey",
    "100MG * 1": "#6F8DB9",
    "100MG * 2": "#6F8DB9",
    "10MG": "slateblue",
    "15MG": "rebeccapurple",
    "200MG * 1": "#44546A",
    "20MG": "indigo",
    "250MG": "navy",
    "25MG10片装": "darkgreen",
    "25MG20片装": "olivedrab",
    "500MG": "crimson",
    "50MG * 2": "#BD2843",
    "75MG7片装": "darkorange",
    "A+C FDC": "Purple",
    "A+C": "navy",
    "A+D FDC": "Violet",
    "A+D": "darkorange",
    "ACEI": "olivedrab",
    "ACEI+C": "darkorange",
    "ACEI+D": "darkorange",
    "ACLASTA (NVR)": "navy",
    "MAT实际发货": "teal",
    "ADALAT (BY6)": "purple",
    "ALENDRONATE SODIUM (S1H)": "saddlebrown",
    "AMLODIPINE BESYLAT (CQY)": "deepskyblue",
    "AMLODIPINE BESYLAT (S5O)": "olivedrab",
    "AN LAI (ZJ5)": "gold",
    "APROVEL (SG9)": "crimson",
    "ARB": "darkgreen",
    "ARB+C": "navy",
    "ARB+D": "navy",
    "ARNI": "deepskyblue",
    "B03A 补血药，铁剂": "navy",
    "B03C 红细胞生成素": "crimson",
    "B03D HIF-PH抑制剂": "darkgreen",
    "ESA": "darkorange",
    "HIF-PHI": "darkgreen",
    "BAI AN XIN (GRU)": "darkgreen",
    "BAYASPIRIN (BAY)": "navy",
    "BB": "crimson",
    "BEI YI (ZJ5)": "olivdedrab",
    "BEI YI (ZJ5)": "pink",
    "BEI YUE (ZJ5)": "purple",
    "Beta Blocker": "olivedrab",
    "Bottom20%": "crimson",
    "BRILINTA (AZN)": "darkorange",
    "CCB": "navy",
    "CLOPIDOGREL BISULF (HDO)": "pink",
    "COAPROVEL (SG9)": "pink",
    "COZAAR (ORG)": "darkorange",
    "DA FEN GAI (SZA)": "darkgreen",
    "DIOVAN (NVR)": "navy",
    "Diuretics": "darkgreen",
    "DPP4": "crimson",
    "DU": "darkorange",
    "ELCITONIN (ASC)": "gold",
    "EN CUN (S1H)": "deepskyblue",
    "ENTRESTO (NVR)": "violet",
    "EXFORGE (NVR)": "maroon",
    "FORSTEO (LLY)": "deepskyblue",
    "FORSTEO PRE-FILLED P 600Y 2.4ML 1": "darkorange",
    "复泰奥": "darkorange",
    "FOSAMAX (ORG)": "olivedrab",
    "FOSAMAX PLUS (ORG)": "darkgreen",
    "FUROSEMIDE (SZO)": "saddlebrown",
    "G03J0\n选择性雌激素\n受体调节剂": "navy",
    "GLP-1": "darkgreen",
    "H04A0\n降钙素": "crimson",
    "H04E0\n甲状旁腺激素\n及类似物": "darkorange",
    "HYZAAR (ORG)": "crimson",
    "INS": "crimson",
    "JI JIA (JSH)": "orchid",
    "JIN ER LI (B-Y)": "purple",
    "KE MI GU (SK4)": "gold",
    "LABA+ICS固定复方制剂": "purple",
    "LAN SHA (BW.)": "c",
    "LOTENSIN (NBJ)": "olivedrab",
    "M05B3\n治疗骨质疏松\n和骨钙失调\n的二膦酸盐类": "darkgreen",
    "MAT数量": "teal",
    "MAT金额": "teal",
    "MIACALCIC (NVR)": "darkorange",
    "Mid-Bottom20%": "pink",
    "Mid20%": "darkorange",
    "MON数量": "navy",
    "MON金额": "navy",
    "MQT数量": "crimson",
    "MQT金额": "crimson",
    "MRA": "olivedrab",
    "NORVASC (VI/)": "crimson",
    "OAD": "navy",
    "OLMETEC PLUS (DSC)": "navy",
    "Others": "grey",
    "PLAGRIL (DRL)": "deepskyblue",
    "PLAVIX (SG9)": "crimson",
    "PROLIA (AAI)": "pink",
    "PTH": "darkorange",
    "RAAS FDC": "darkorange",
    "RAAS平片(ARB+ACEI)": "crimson",
    "RISEDRONATE SODIUM (YKJ)": "coral",
    "SAMA+SABA固定复方制剂": "deepskyblue",
    "SERM": "navy",
    "SGLT2": "darkorange",
    "SHI HUI DA (JTF)": "pink",
    "SHUAI TAI (LUU)": "olivedrab",
    "SHUAI XIN (LUU)": "darkgreen",
    "SHUAI XIN/SHUAI TAI (LUU)": "darkgreen",
    "SI DI NUO (S-Y)": "saddlebrown",
    "TALCOM (SI6)": "teal",
    "Top-Mid20%": "olivedrab",
    "Top20%": "darkgreen",
    "趋势-P12M": "crimson",
    "趋势-P3M": "darkorange",
    "趋势-P6M": "olivedrab",
    "TUO PING (ZHT)": "deepskyblue",
    "TZD & PPAR全激动剂": "saddlebrown",
    "TZD": "saddlebrown",
    "V03B 中药和中成药": "darkorange",
    "VALSARTAN (QJX)": "pink",
    "VBP品种": "crimson",
    "XIE AN ZHI (ZHU)": "mediumslateblue",
    "XIE KE (JC4)": "navy",
    "XIN FU TAI (XIL)": "teal",
    "XIN FU TAI PRE-FILLED P 600Y 2.4ML 1": "deepskyblue",
    "欣复泰水针": "deepskyblue",
    "XIN FU TAI VIAL DRY 200IU 10": "navy",
    "欣复泰粉针": "navy",
    "XIN LI TAN (SI6)": "teal",
    "YI DA LI (ZUP)": "olive",
    "YI GU (CTA)": "crimson",
    "YI SU (JJJ)": "coral",
    "YI YE (AU3)": "coral",
    "YIN DUO (HZH)": "pink",
    "YOU LI WEI (NJ2)": "gold",
    "ZHEN GU (S60)": "crimson",
    "ZHEN GU VIAL DRY 200IU 1": "crimson",
    "珍固": "crimson",
    "α糖苷酶抑制剂": "olivedrab",
    "β受体阻断剂": "teal",
    "一线城市": "navy",
    "万脉舒（H2C）": "navy",
    "三线城市": "teal",
    "丙卡特罗": "navy",
    "丙戊酸钠": "navy",
    "丙酸倍氯米松": "crimson",
    "丙酸氟替卡松": "darkorange",
    "中标仿制": "crimson",
    # "中等的20%（50分）": "darkorange",
    "二甲双胍": "navy",
    "二线城市": "crimson",
    "二羟丙茶碱": "tomato",
    "二羟丙茶碱氯化钠": "teal",
    "五线城市": "darkorange",
    "京可新": "darkgreen",
    "京可新（ZXJ）": "darkgreen",
    "京必舒新（ZXJ）": "darkorange",
    "京诺": "olivedrab",
    "京诺（ZXJ）": "pink",
    "代文": "darkorange",
    "代文（NVR）": "navy",
    "代文（NVU）": "navy",
    "伊伐布雷定": "navy",
    "伊疏（S.I）": "saddlebrown",
    "伊达力": "olive",
    "伊达力（ZHI）": "olive",
    "伊达力（ZUP）": "olive",
    "伏格列波糖": "teal",
    "优力平": "gold",
    "优力平（ZLU）": "saddlebrown",
    "依固": "crimson",
    "依固（C2T）": "crimson",
    "依固（CTA）": "crimson",
    "依度沙班": "deepskyblue",
    "依折麦布": "crimson",
    "依替膦酸二钠": "teal",
    "依苏": "coral",
    "依那普利": "saddlebrown",
    "依那普利（JJJ）": "saddlebrown",
    "依那普利（YAZ）": "saddlebrown",
    "依那普利拉": "olivedrab",
    "依降钙素": "olivedrab",
    "信立坦": "purple",
    "信立坦（SI6）": "teal",
    "信立明": "teal",
    "信立明（SI6）": "teal",
    "信达悦（SI6）": "teal",
    "倍利舒": "purple",
    "倍博特": "maroon",
    "倍博特（NVU）": "maroon",
    "倍怡": "pink",
    "倍怡（ZJ5）": "pink",
    "倍悦": "crimson",
    "倍悦（ZJ5）": "purple",
    "倍林达": "darkorange",
    "傲坦": "deepskyblue",
    "傲坦（DCG）": "navy",
    "傲坦（DSC）": "navy",
    "克赛（AVS）": "crimson",
    "兰沙": "c",
    "兰沙（B4W）": "crimson",
    "兰沙（BW.）": "darkgreen",
    # "其他": "Deepskyblue",
    # "其他": "grey",
    "其他品种": "grey",
    "其他科室": "grey",
    "其他非集采品种": "purple",
    "内分泌科": "#FAA53A",
    "内分泌科": "darkgreen",
    "冠心病": "#6F8DB9",
    "冠爽": "navy",
    "冠爽（BJP）": "crimson",
    "冠爽（SHN）": "crimson",
    "利伐沙班": "rebeccapurple",
    "利塞膦酸钠": "purple",
    "利塞膦酸钠片": "gold",
    "利塞膦酸钠片（YKJ）": "gold",
    "利格列汀": "darkorange",
    "力清之": "darkorange",
    "力清之（KW.）": "darkorange",
    "加巴喷丁": "gold",
    "匹伐他汀": "teal",
    "匹伐他汀（JN.）": "dodgerblue",
    "匹伐他汀钙片": "olivedrab",
    "匹伐他汀钙片（S1Q）": "navy",
    "匹伐他汀钙片（SI6）": "olivedrab",
    "华东区": "navy",
    "华中区": "darkorange",
    "华北区": "darkgreen",
    "华南区": "teal",
    "华法林": "darkorange",
    "华西区": "crimson",
    "卒中": "#2B9B33",
    "单价": "navy",
    "单纯高血压": "#44546A",
    "卡托普利": "darkorange",
    "卡托普利片": "grey",
    "卡格列净": "navy",
    "厄贝沙坦,氢氯噻嗪": "royalblue",
    "厄贝沙坦": "#6F8DB9",
    "厄贝沙坦": "navy",
    "厄贝沙坦氢氯噻嗪": "royalblue",
    "双膦酸盐类": "darkgreen",
    "口服溶液": "deepskyblue",
    "口服片剂": "navy",
    "可定": "crimson",
    "可定（A5Z）": "crimson",
    "可定（AZN）": "crimson",
    "吉加": "orchid",
    "吉加（H9R）": "orchid",
    "吉加（JSH）": "orchid",
    "吲哚布芬": "crimson",
    "吸入性糖皮质激素(ICS)": "navy",
    "咪达普利": "coral",
    "唑来膦酸": "navy",
    "唑来膦酸（SHR）": "pink",
    "唑来膦酸（YAZ）": "darkorange",
    "唑来膦酸注射液": "navy",
    "唑来膦酸注射液（KEU）": "saddlebrown",
    "唑来膦酸注射液（SK4）": "saddlebrown",
    "喹那普利": "saddlebrown",
    "四线城市": "darkgreen",
    "国产阿司匹林": "grey",
    "地舒单抗": "deepskyblue",
    "坎地沙坦": "#FAA53A",
    "坎地沙坦": "olivedrab",
    "埃格列净": "darkorange",
    "培哚普利": "purple",
    "培哚普利氨氯地平": "navy",
    "复傲坦（DCG）": "deepskyblue",
    "复方妥英麻黄茶碱": "olivedrab",
    "复方胆氨": "darkgreen",
    "复方茶碱麻黄碱": "purple",
    "复泰奥（LYG）": "deepskyblue",
    "多索茶碱": "navy",
    "天泉乐宁（FTQ）": "olivedrab",
    "奥卡西平": "darkorange",
    "奥美沙坦": "deepskyblue",
    "奥美沙坦（BW.）": "deepskyblue",
    "奥美沙坦（FTQ）": "deepskyblue",
    "奥美沙坦（GY0）": "saddlebrown",
    "奥美沙坦（SI6）": "teal",
    "奥美沙坦酯": "#2B9B33",
    "奥美沙坦酯片（S6N）": "darkgreen",
    "妥洛特罗": "teal",
    "孟鲁司特": "navy",
    "安博维": "crimson",
    "安博维（SA9）": "crimson",
    "安博维（SG9）": "crimson",
    "安博诺（SA9）": "pink",
    "安来": "gold",
    "安来（ZJ5）": "gold",
    "密固达": "navy",
    "密固达（NVR）": "navy",
    "密固达（NVU）": "navy",
    "密盖息": "darkorange",
    "密盖息（NVR）": "darkorange",
    "密盖息（NVU）": "darkorange",
    "富利他之（ZHI）": "rebeccapurple",
    "尤佳": "teal",
    "尤佳（TOF）": "darkgreen",
    "尤尼舒（J/G）": "olivedrab",
    "左乙拉西坦": "crimson",
    "左乙拉西坦（SI6）": "teal",
    "左乙拉西坦（ZJO）": "darkgreen",
    "左乙拉西坦片（CQU）": "crimson",
    "左乙拉西坦片（ZXJ）": "darkorange",
    "左旋氨氯地平": "darkorange",
    "布地奈德": "navy",
    "帅信": "darkgreen",
    "帅信/帅泰": "saddlebrown",
    "帅泰": "olivedrab",
    "希佳（C2T）": "darkorange",
    "希佳（NJ2）": "darkorange",
    "希弗全（A1L）": "darkgreen",
    "带量品种": "crimson",
    "平欣": "mediumslateblue",
    "开浦兰（UCB）": "navy",
    "异丙肾上腺素": "grey",
    "心内科": "#44546A",
    "心内科": "teal",
    "心力衰竭": "Saddlebrown",
    "必洛斯": "darkgreen",
    "恒格列净": "darkgreen",
    "恩存": "deepskyblue",
    "恩格列净": "crimson",
    "慢性肾病": "#FAA53A",
    "托吡酯": "teal",
    "托妥": "purple",
    "托妥（NJ2）": "purple",
    "托平（ZHT）": "deepskyblue",
    "抗白三烯类药物(LTRA)": "teal",
    "拉莫三嗪": "purple",
    "拉贝洛尔": "olivedrab",
    "拜阿司匹灵": "navy",
    "搏力高": "mediumslateblue",
    "搏力高（ZYG）": "mediumslateblue",
    "斯迪诺": "saddlebrown",
    "斯迪诺（LU6）": "teal",
    "斯迪诺（S-Y）": "teal",
    "旗舰社区": "crimson",
    "无以上适应症": "Purple",
    "普仑司特": "crimson",
    "普伐他汀": "olivedrab",
    "普内科": "#2B9B33",
    "普内科": "saddlebrown",
    "普洛静（GTW）": "pink",
    "普瑞巴林": "olivedrab",
    "普罗力": "pink",
    "普罗力（AAI）": "pink",
    "普通社区": "pink",
    "替格瑞洛": "darkorange",
    "替米沙坦": "#ED94B6",
    "替米沙坦": "darkgreen",
    # "最好的20%（90分）": "darkgreen",
    # "最差的20%（10分）": "crimson",
    "未中标仿制": "dodgerblue",
    "未中标原研": "navy",
    "来适可XL（NVR）": "orchid",
    "来适可XL（NVU）": "orchid",
    "标准盒数（万盒）": "crimson",
    "格列奈类": "violet",
    "欣复泰": "teal",
    "欣复泰（XIL）": "teal",
    "欧美利（GY0）": "saddlebrown",
    "比伐芦定": "teal",
    "比伐芦定\n海南双成药业股份有限公司": "darkorange",
    "比伐芦定\n齐鲁制药集团": "deepskyblue",
    "比索洛尔": "darkorange",
    "比索洛尔": "navy",
    "氟伐他汀": "darkgreen",
    "氨氯地平": "darkgreen",
    "氨茶碱": "darkorange",
    "氯吡格雷": "teal",
    "氯沙坦": "#BD2843",
    "氯沙坦": "darkorange",
    "氯沙坦氢氯噻嗪": "gold",
    "氯沙坦钾": "darkorange",
    "氯硝西泮": "deepskyblue",
    "沙丁胺醇": "crimson",
    "沙库巴曲缬沙坦": "Olive",
    "沙库巴曲缬沙坦": "violet",
    "沙库巴曲缬沙坦钠": "Olive",
    "沙格列汀": "teal",
    "法安明（PHA）": "rebeccapurple",
    "波立维": "crimson",
    "注射剂": "crimson",
    "注射用那屈肝素钙": "deepskyblue",
    "注射用那屈肝素钙（DG+）": "deepskyblue",
    "泰仪": "olivedrab",
    "泰加宁": "teal",
    "泰加宁（SI6）": "teal",
    "泰加宁\n深圳信立泰药业股份有限公司": "teal",
    "泰嘉": "darkgreen",
    "泽朗": "crimson",
    "泽朗\n江苏豪森药业集团有限公司": "crimson",
    "洛伐他汀": "saddlebrown",
    "洛汀新": "olivedrab",
    "洛汀新（NBJ）": "olivedrab",
    "洛汀新（NVU）": "olivedrab",
    "特布他林": "navy",
    "特立帕肽": "pink",
    "环仑特罗": "darkgreen",
    "环索奈德": "darkgreen",
    "珍固": "crimson",
    "珍固（S60）": "crimson",
    "班布特罗": "darkorange",
    "瑞旨": "darkgreen",
    "瑞旨（S6B）": "olivedrab",
    "瑞旨（S7O）": "olivedrab",
    "瑞舒伐他汀": "crimson",
    "瑞舒伐他汀（C2T）": "dodgerblue",
    "瑞舒伐他汀（LEK）": "olive",
    "瑞舒伐他汀（NJ2）": "dodgerblue",
    "瑞舒伐他汀（NVU）": "olive",
    "瑞舒伐他汀钙片（ZHI）": "orchid",
    # "百安新": "darkgreen",
    "百安新（YAZ）": "darkgreen",
    "益盖宁": "teal",
    "益盖宁（ASC）": "pink",
    "短效β2受体激动剂(SABA)": "crimson",
    "短效抗胆碱剂(SAMA)": "olivedrab",
    "硝苯地平": "purple",
    "硝苯地平缓释片": "crimson",
    "硫酸氢氯吡格雷片": "saddlebrown",
    "硫酸镁": "darkgreen",
    "磺脲类": "purple",
    "社区医院": "crimson",
    "神内科": "#ED94B6",
    "神内科": "darkorange",
    "福善美": "olivedrab",
    "福善美（MSD）": "olivedrab",
    "福善美（MSG）": "olivedrab",
    "福美加": "darkgreen",
    "福美加（MSD）": "darkgreen",
    "福美加（MSG）": "darkgreen",
    "福莫特罗": "crimson",
    "福辛普利": "teal",
    "科素亚": "darkorange",
    "科素亚（MHU）": "darkorange",
    "科素亚（MSG）": "darkorange",
    "科苏": "darkgreen",
    "穗悦": "olivedrab",
    "立普妥": "navy",
    "立普妥（PFZ）": "navy",
    "立普妥（VI/）": "navy",
    "立迈青（AHK）": "darkorange",
    "等级医院": "navy",
    "米格列醇": "crimson",
    # "糖尿病": "#ED94B6",
    "维格列汀": "crimson",
    "缓宁": "gold",
    "缬克（JC4）": "purple",
    "缬沙坦,氨氯地平": "maroon",
    "缬沙坦": "#44546A",
    "缬沙坦": "crimson",
    "缬沙坦氢氯噻嗪": "pink",
    "缬沙坦氨氯地平": "maroon",
    "美卡素": "purple",
    "美卡素（B.I）": "purple",
    "美托洛尔": "olivedrab",
    "美托洛尔常释剂型": "teal",
    "美托洛尔缓释剂型": "crimson",
    "美托洛尔缓释片": "crimson",
    "美洛林": "deepskyblue",
    "美百乐镇（DCG）": "coral",
    "美百乐镇（DSC）": "coral",
    "美阿沙坦": "pink",
    "美阿沙坦钾片": "pink",
    "老干科": "#BD2843",
    "老干科": "navy",
    "肝素": "crimson",
    "肾内科": "#6F8DB9",
    "肾内科": "crimson",
    "舒降之（MHU）": "dodgerblue",
    "艾司洛尔": "crimson",
    "艾普拉唑": "crimson",
    "苯巴比妥": "pink",
    "茚达特罗": "purple",
    "茶碱,盐酸甲麻黄碱,暴马子浸膏": "saddlebrown",
    "茶碱": "crimson",
    "螺内酯": "navy",
    "血脂异常": "#BD2843",
    "西格列汀": "navy",
    "诺欣妥": "crimson",
    "诺欣妥（NVU）": "violet",
    "贝尼地平": "darkgreen",
    "贝那普利,氨氯地平": "salmon",
    "贝那普利": "coral",
    "贝那普利": "Purple",
    "贝那普利氨氯地平": "salmon",
    "赖诺普利": "pink",
    "赛倍畅（JJY）": "saddlebrown",
    "赛博利": "gold",
    "赛博利（S1E）": "gold",
    # "较好的20%（70分）": "olivedrab",
    # "较差的20%（30分）": "pink",
    "辛伐他汀": "darkorange",
    "辛可（GXN）": "olive",
    "达格列净": "teal",
    "达比加群酯": "dodgerblue",
    "达芬盖（SZA）": "dodgerblue",
    "迪之雅": "olive",
    "速避凝（A3N）": "purple",
    "那屈肝素钙注射液（JJY）": "saddlebrown",
    "邦之": "crimson",
    "邦之（JBI）": "saddlebrown",
    "邦之（SFO）": "saddlebrown",
    "金尔力": "purple",
    "金尔力（B-Y）": "purple",
    "销售基恩（万元）": "teal",
    "长效β2受体激动剂(LABA)": "tomato",
    "长效抗胆碱剂(LAMA)": "darkgreen",
    "阿乐": "darkorange",
    "阿乐（SDS）": "darkorange",
    "阿仑膦酸钠,维生素D3": "darkgreen",
    "阿仑膦酸钠": "darkorange",
    "阿仑膦酸钠维生素D3": "darkgreen",
    "阿利沙坦": "teal",
    "阿利沙坦酯": "Deepskyblue",
    "阿卡波糖咀嚼片": "deepskyblue",
    "阿卡波糖片剂": "navy",
    "阿司匹林": "navy",
    "阿哌沙班": "darkgreen",
    "阿托伐他汀": "navy",
    "阿托伐他汀（FJ.）": "pink",
    "阿托伐他汀（FXG）": "olive",
    "阿托伐他汀（GI2）": "olive",
    "阿托伐他汀（HNQ）": "deepskyblue",
    "阿托伐他汀（QIL）": "deepskyblue",
    "阿托伐他汀（ZLU）": "deepskyblue",
    "阿托伐他汀钙分散片（G6B）": "gold",
    "阿格列汀": "darkgreen",
    "阿罗洛尔": "darkgreen",
    "阿罗洛尔": "darkorange",
    "阿齐沙坦": "saddlebrown",
    "降钙素": "crimson",
    "雅施达": "saddlebrown",
    "雅施达（SVU）": "saddlebrown",
    "雅施达（TSV）": "saddlebrown",
    "集采品种": "grey",
    "雷洛昔芬": "gold",
    "雷米普利": "deepskyblue",
    "非VBP品种": "teal",
    "非奈利酮": "crimson",
    "非带量品种": "teal",
    "非洛地平": "saddlebrown",
    "非类固醇类呼吸道消炎药": "saddlebrown",
    "马来酸依那普利叶酸片（AU3）": "grey",
    "高尿酸": "Deepskyblue",
    # "高血压": "#44546A",
    "高血压+冠心病": "#6F8DB9",
    "高血压+卒中": "#2B9B33",
    "高血压+心力衰竭": "Saddlebrown",
    "高血压+慢性肾病": "#FAA53A",
    "高血压+糖尿病": "#ED94B6",
    "高血压+血脂异常": "#BD2843",
    "高血压+高尿酸": "Deepskyblue",
    "鲑降钙素": "crimson",
    "鲑鱼降钙素": "crimson",
    "黄嘌呤类": "darkorange",
    "齐征": "pink",
    "齐征（QLU）": "pink",
    # "ACEI": "#6F8DB9",
    # "ACEI": "crimson",
    # "ARB": "#44546A",
    # "ARB": "teal",
    # "ARNI": "#EE82EE",
    # "ARNI": "violet",
    # "D1-D2": "deepskyblue",
    # "D3-D5": "dodgerblue",
    # "D6-D8": "royalblue",
    # "D9-D10": "navy",
    # "比索洛尔": "navy",
    # "硝苯地平": "crimson",
    # "美托洛尔": "navy",
    # "阿罗洛尔": "darkorange",
    # "非洛地平": "navy",
}

# COLOR_LIST = [
#     "#44546A",
#     "#6F8DB9",
#     "#BD2843",
#     "#ED94B6",
#     "#FAA53A",
#     "#2B9B33",
#     "Deepskyblue",
#     "Saddlebrown",
#     "Purple",
#     "Olivedrab",
#     "Pink",
# ]

COLOR_LIST = [
    "teal",
    "crimson",
    "navy",
    "darkorange",
    "darkgreen",
    "olivedrab",
    "purple",
    "pink",
    "deepskyblue",
    "saddlebrown",
    "tomato",
    "cornflowerblue",
    "magenta",
]

CMAP_QUAL = ListedColormap(COLOR_LIST)
CMAP_NORM = plt.get_cmap("PiYG")
RANDOM_CMAP = mpl.colors.ListedColormap(np.random.rand(256, 3))


class Colors:
    def __init__(
        self,
        color_dict: Dict[str, str] = COLOR_DICT,
        cmap_qual: mpl.colors.Colormap = CMAP_QUAL,
        cmap_norm: mpl.colors.Colormap = CMAP_NORM,
    ):
        self.color_dict = color_dict
        self.cmap_qual = cmap_qual
        self.cmap_norm = cmap_norm
        self.iter_colors = cycle(self.cmap_qual(i) for i in range(self.cmap_qual.N))

    def get_color(self, name: str) -> str:
        color = self.color_dict.get(name, next(self.iter_colors))
        return color

    def get_colors(
        self,
        n: int,
        color: str = None,
        hue: pd.Series = None,
        random_color: bool = True,
    ) -> list:
        if color is None:
            color = self.cmap_qual.colors[0]

        if hue is None:
            if random_color:
                cmap = RANDOM_CMAP
            else:
                cmap = ListedColormap([color])
            colors = [cmap(i) for i in range(n)]
        else:
            # 如果hue字段是numeric
            if pd.api.types.is_numeric_dtype(hue.dtype):
                cmap = self.cmap_norm
                norm = mpl.colors.Normalize(vmin=min(hue), vmax=max(hue))
                colors = [cmap(norm(value)) for value in hue]
            # 如果hue字段是categorical
            else:
                cmap = self.cmap_qual
                levels, categories = pd.factorize(hue)

                colors = [self.color_dict.get(categories[i], cmap(i)) for i in levels]

        return cmap, colors
